<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [1]:
x = 10
assert x >= 0, "x is becoming negative!"

print(x)

10


In [2]:
x = -1
assert x >= 0, "x is becoming negative!"

print(x)

AssertionError: x is becoming negative!

### 1.2 try-except

In [3]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')


Give me a number and I will calculate its square.1
The square of 1 is 1!


In [4]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.hahaha


ValueError: invalid literal for int() with base 10: 'hahaha'

In [5]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.hahaha
Oh oh! I cannot square hahaha!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [45]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c   


In [46]:
funny_add(1, 2)

121

In [11]:
funny_add(a=1, b=2)

121

In [47]:
funny_add(c=3, b=1, a=2)

312

In [13]:
funny_add(1, c=3, b=2)

321

In [14]:
funny_add(1, b=2)

121

In [15]:
funny_add(a=2, 1) 

SyntaxError: positional argument follows keyword argument (2196417011.py, line 1)

### 2.2 Docstrings

In [16]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c

help(funny_add)


Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [19]:
def my_function(angle, trig_function): 
        return trig_function(angle)


my_function(np.pi/2, np.sin)        

1.0

In [18]:
my_function(np.pi/2, np.cos)   

6.123233995736766e-17

In [20]:
my_function(np.pi/2, lambda x: np.cos(2*x))  

-1.0

### 2.4 More unpacking

In [21]:
x, y, z = [1, 2, 3]
print(x, y, z)


1 2 3


In [22]:
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [25]:
x, *y, z = np.array([1, 2, 3, 4, 5])   
print(x, y, z)

1 [2, 3, 4] 5


In [26]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [35]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])


def add(x, y):
    return x+y

print(add(x, y))

def subtract(x, y):
    return x-y

print(subtract(x, y))

def multiply(x, y):
    return x*y

print(multiply(x, y))

def divide(x, y):
    return x/y
    if x == 0  or y == 0:
        exit()
    else:
        return x/y
    
    assert x >= 0, "x is becoming negative!"
    
    assert y >= 0, "y is becoming negative!"

print(divide(x, y))
    






[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 2 :  A better calculator II

In [44]:

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

    
def add(x, y):
    try:
        return x+y
    except:
        print(f"Oh oh! I cannot add")

print(add(x, y))

def subtract(x, y):
    try:
        return x-y
    except:
        print(f"Oh oh! I cannot subtract")

print(subtract(x, y))

def multiply(x, y):
    try:
        return x*y
    except:
        print(f"Oh oh! I cannot mulitply")

print(multiply(x, y))

def divide(x, y):
    return x/y
    try:
        if x == 0  or y == 0:
            exit()
        else:
            return x/y
    except:
        print(f"Oh oh! I cannot divide")
    

print(divide(x, y))



[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]
