<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [1]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting("Super Man")
    
    

'Hello Super Man!'

In [2]:
def greeting2(name):
    if name == 'Batman' or 'Black Widow':
        return f'Hello {name}! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting2('Superman')

'Hello Superman! So, nice to meet you!'

In [3]:
greet=greeting(name='Super Man')
print(greet)

Hello Super Man!


### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [4]:
my_short_function = lambda name: f"Hello {name}!"

my_short_function(name="Super Man")

'Hello Super Man!'

In [5]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [6]:
sorted(numbers, key=lambda x: x[1])     

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [7]:
sorted(numbers, key=lambda x: sum(x))  

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [8]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'


In [9]:
greeting()

'Hello no one!'

In [10]:
print()

## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

## Exercise 1 :  Do you know why?

There is no need for an else statement as the return function terminates the current function and under the condition the 'if' statement does not work, the code underneath 'if' will still work







## Exercise 2 :  Calculator functions

In [13]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(x, y):
    return x+y

print(add(x, y))

def subtract(x, y):
    return x-y

print(subtract(x, y))

def multiply(x, y):
    return x*y

print(multiply(x, y))

def divide(x, y):
    return x/y
    if x == 0  or y == 0:
        exit()
    else:
        return x/y

print(divide(x, y))
    



[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [15]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

def max_info(numbers): 
    np_numbers=np.array(numbers)
    return np_numbers.max(), np_numbers.argmax()

print(max_info(numbers))

(83, 2)
