<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }


### 1.2 Accessing data from a list (or array)

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

print(py_super_names[0])


Natasha Romanoff
Black Widow


In [5]:
print(py_super_names[2])    

print(py_super_names[-1])   

Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [7]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])


Black Widow


### 1.4 Higher dimensional lists

In [9]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]


## 2 Lists vs. Arrays

### 2.1 Size

In [11]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      

len(py_list_2d)

len(np_array_2d)

10

### 2.2 Arrays are fussy about type

In [12]:
py_list = [1, 1.5, 'A']
np.array(py_list)


array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [16]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
     
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [21]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2




[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [20]:
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [24]:
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

py_list**2                      # Won't work!  


TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [27]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

py_list == 3     

py_list > 3      # Won't work!


TypeError: '>' not supported between instances of 'list' and 'int'

In [32]:
np_array == 3  

np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

sum(py_list)     


15

In [34]:
max(py_list)     

5

In [35]:
min(py_list)     # min() is a base Python function

1

In [36]:
py_list.sum()   # Won't work!

AttributeError: 'list' object has no attribute 'sum'

In [37]:
np_array.sum()

15

In [38]:
np_array.mean()

3.0

In [39]:
np_array.max()

5

In [40]:
np_array.min()

1

## Exercise 1 :  Total recall?

1. Lists and arrays are both ways to store data and *to access data in lists and arrays we wil need to use an index corresponding to the data's position.*

2. One difference is that using a list is more convenient because arrays use a single data type. Another difference is that when adding another list, it just adds on the previous list whereas for arrays, the numbers are added to each other.

3. A dictionary has data paired with *a key.*






## Exercise 2 :  Index me

In [42]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])   # Prints 'a1'
print(py_list[2])   # Prints 'c3'
print(py_list[4])   # Prints 'e5'
print(py_list[6])   # Prints 'g7'
print(py_list[8])   # Prints 'i9'




a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [48]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()                  
print(superhero_info["Tony Stark"])

superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()  
print(superhero_info['Natasha Romanoff'])

superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info["Stephen Strange"])

IRON MAN
BLACK WIDOW
DOCTOR STRANGE


## Exercise 4 :  How many ones

In [2]:
py_list = [45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]  
np_array = np.array(py_list)

x = np_array

np.count_nonzero((x == 1))




9