<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [6]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

x[0]




'a1'

In [7]:
x[-1]

'j10'

In [8]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [9]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [10]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [11]:
x[5:]

array(['f6', 'g7', 'h8', 'i9', 'j10'], dtype='<U3')

In [12]:
x[:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [13]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

In [14]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [15]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)


[False False False  True  True  True  True  True  True  True]


In [16]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [18]:
np_array[~(np_array > 3)]                         # '~' means 'NOT'

array([1, 2, 3])

In [19]:
np_array[(np_array > 3) & (np_array < 8)]         # '&' means 'AND'

array([4, 5, 6, 7])

In [20]:
np_array[(np_array < 3) | (np_array > 8)]         # '|' means 'OR'

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [21]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[3]        # What is at position 4 (index 3)?


[4, 'D']

In [22]:
py_list_2d[3][0]     # FIRST element at position 4 (index 3)

4

In [23]:
py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

In [24]:
py_list_2d[:3][0]

[1, 'A']

In [25]:
py_list_2d[3:6][0]

[4, 'D']

### 1.4 Indexing & Slicing 2D Arrays

In [27]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[3]       # What is at position 4 (index 3)?

array(['4', 'D'], dtype='<U21')

In [28]:
np_array_2d[3, 0]    # FIRST element at position 4 (index 3)

'4'

In [29]:
np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

In [30]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U21')

In [31]:
np_array_2d[3:6, 0]

array(['4', '5', '6'], dtype='<U21')

In [32]:
np_array_2d[:, 0]

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

### 1.5 Growing lists

In [33]:
x=[1]*10
x               


[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [34]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x

[1, 2, 3, 4]

In [35]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x

[1, 2, 3, 4]

In [36]:
x=[1]
x+= [2, 3, 4]
x

[1, 2, 3, 4]

In [37]:
x=[1]
x= [2, 3, 4] + x
x

[2, 3, 4, 1]

In [38]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [39]:
a=(1, 2, 3)     # Define tuple

print(a[0])    # Access data


1


In [40]:
# The following will NOT work
a[0]=-1
a[0] += [10]

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [41]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!

In [44]:
x=[1, 2, 3]
y=x.copy() 
z=x.copy()

y

[1, 2, 3]

## Exercise 1 :  Total recall?

| term| brief desription |
| :---| ---:|
| subesetting| Refers to selecting *a subset* |
|Indexing| Refers to selecting an element|
|slicing | Refers to selecting a range of elements|
|Masking | Refers to *subsetting* |




## Exercise 2 :  Show me the ‘odd’ letters

In [50]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

x = np_array_2d[:, 0]

x


array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [53]:
x = x.astype(int)
x

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [54]:
x%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [58]:
x = x%2
my_mask = x > 0
print(my_mask)

[ True  True False False  True  True False False False  True]


In [59]:
np_array[my_mask]

array([ 1,  2,  5,  6, 10])

In [4]:
py_list=["A", "C", "E", "G", "I"]

np_array=np.array(py_list)

x = np_array

x[:]



array(['A', 'C', 'E', 'G', 'I'], dtype='<U1')